"use client";

import { useEffect, useState, useCallback } from "react";
import { useSearchParams } from "next/navigation";
import { Suspense } from "react";

const C = {
  bg: "#09090B",
  surface: "#111113",
  surface2: "#18181B",
  border: "rgba(255,255,255,0.07)",
  borderStrong: "rgba(255,255,255,0.14)",
  accent: "#635BFF",
  accentDim: "rgba(99,91,255,0.12)",
  green: "#22C55E",
  greenDim: "rgba(34,197,94,0.12)",
  text: "#FAFAFA",
  textSec: "rgba(250,250,250,0.6)",
  textMuted: "rgba(250,250,250,0.35)",
};

function CheckCircle() {
  return (
    <svg width="72" height="72" viewBox="0 0 72 72" fill="none" style={{ animation: "popIn 0.5s cubic-bezier(0.175, 0.885, 0.32, 1.275) both" }}>
      <circle cx="36" cy="36" r="36" fill={C.greenDim} />
      <circle cx="36" cy="36" r="28" fill="rgba(34,197,94,0.15)" />
      <path d="M22 36L31 45L50 27" stroke={C.green} strokeWidth="3" strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  );
}

function SuccessContent() {
  const searchParams = useSearchParams();
  const method = searchParams.get("method");
  const [orderId, setOrderId] = useState("");
  const [invoiceId, setInvoiceId] = useState("");
  const [date, setDate] = useState("");

  useEffect(() => {
    setOrderId("PF-" + Math.floor(100000 + Math.random() * 900000));
    setInvoiceId("INV-" + Math.floor(10000 + Math.random() * 90000));
    setDate(new Date().toLocaleDateString("da-DK", { day: "numeric", month: "long", year: "numeric" }));
  }, []);

  const paymentLabel = method === "applepay" ? "Apple Pay" : method === "googlepay" ? "Google Pay" : "Visa **** 4242";

  const downloadInvoice = useCallback(() => {
    const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>Invoice ${invoiceId}</title><style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:-apple-system,BlinkMacSystemFont,sans-serif;padding:48px;max-width:700px;margin:0 auto;color:#1a1a2e}.header{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:48px}.logo{font-size:24px;font-weight:800;letter-spacing:-0.03em;color:#635BFF}.badge{background:#635BFF;color:#fff;font-size:10px;font-weight:700;padding:4px 12px;border-radius:100px;letter-spacing:0.06em}table{width:100%;border-collapse:collapse;margin:24px 0}th{text-align:left;font-size:11px;font-weight:600;color:#888;text-transform:uppercase;letter-spacing:0.08em;padding:8px 0;border-bottom:2px solid #eee}td{padding:14px 0;border-bottom:1px solid #f0f0f0;font-size:14px}.total td{border-bottom:none;font-weight:700;font-size:16px;padding-top:16px}.meta{display:grid;grid-template-columns:1fr 1fr;gap:24px;margin-bottom:32px}.meta-label{font-size:11px;font-weight:600;color:#888;text-transform:uppercase;letter-spacing:0.06em;margin-bottom:4px}.meta-value{font-size:14px;font-weight:500}.footer{margin-top:48px;padding-top:24px;border-top:1px solid #eee;font-size:12px;color:#999;text-align:center}</style></head><body><div class="header"><div><div class="logo">PayFlow</div><div style="font-size:12px;color:#888;margin-top:4px">Invoice</div></div><span class="badge">DEMO</span></div><div class="meta"><div><div class="meta-label">Invoice number</div><div class="meta-value">${invoiceId}</div></div><div><div class="meta-label">Date</div><div class="meta-value">${date}</div></div><div><div class="meta-label">Order ID</div><div class="meta-value">${orderId}</div></div><div><div class="meta-label">Payment method</div><div class="meta-value">${paymentLabel}</div></div></div><table><thead><tr><th>Description</th><th style="text-align:right">Amount</th></tr></thead><tbody><tr><td>Example Product<br><span style="font-size:12px;color:#888">Your Brand</span></td><td style="text-align:right">$149.00</td></tr><tr><td>Tax (25%)</td><td style="text-align:right">$37.25</td></tr><tr class="total"><td>Total</td><td style="text-align:right">$186.25</td></tr></tbody></table><div class="footer">This is a demo invoice generated by PayFlow. No real payment was processed.<br>Built by Sloth Studio</div></body></html>`;
    const blob = new Blob([html], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${invoiceId}.html`;
    a.click();
    URL.revokeObjectURL(url);
  }, [invoiceId, date, orderId, paymentLabel]);

  return (
    <div style={{ minHeight: "100vh", background: C.bg, display: "flex", flexDirection: "column" }}>
      <header style={{ borderBottom: `1px solid ${C.border}`, padding: "0 24px", height: "56px", display: "flex", alignItems: "center", background: C.surface }}>
        <span style={{ fontWeight: 700, fontSize: "16px", letterSpacing: "-0.02em", color: C.text }}>PayFlow</span>
      </header>

      <main style={{ flex: 1, display: "flex", justifyContent: "center", alignItems: "flex-start", padding: "64px 24px 120px" }}>
        <div style={{ width: "100%", maxWidth: "560px" }}>
          <div style={{ display: "flex", justifyContent: "center", marginBottom: "28px" }}><CheckCircle /></div>

          <h1 style={{ textAlign: "center", fontSize: "30px", fontWeight: 800, letterSpacing: "-0.04em", margin: "0 0 8px", color: C.text }}>Payment Successful</h1>
          <p style={{ textAlign: "center", fontSize: "15px", color: C.textSec, margin: "0 0 40px" }}>Your order has been confirmed. This is a demo — no real payment was processed.</p>

          {/* Order receipt card */}
          <div style={{ background: C.surface, border: `1px solid ${C.borderStrong}`, borderRadius: "12px", padding: "28px", marginBottom: "16px" }}>
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "20px" }}>
              <h2 style={{ fontSize: "15px", fontWeight: 700, margin: 0, letterSpacing: "-0.02em" }}>Order Receipt</h2>
              <span style={{ background: C.greenDim, color: C.green, fontSize: "10px", fontWeight: 700, padding: "3px 10px", borderRadius: "100px", letterSpacing: "0.06em" }}>COMPLETED</span>
            </div>

            <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "16px", marginBottom: "20px" }}>
              <div><div style={{ fontSize: "10px", fontWeight: 600, color: C.textMuted, textTransform: "uppercase", letterSpacing: "0.08em", marginBottom: "4px" }}>Order ID</div><div style={{ fontSize: "14px", fontWeight: 600, fontFamily: "monospace", letterSpacing: "0.03em" }}>{orderId}</div></div>
              <div><div style={{ fontSize: "10px", fontWeight: 600, color: C.textMuted, textTransform: "uppercase", letterSpacing: "0.08em", marginBottom: "4px" }}>Invoice</div><div style={{ fontSize: "14px", fontWeight: 600, fontFamily: "monospace", letterSpacing: "0.03em" }}>{invoiceId}</div></div>
              <div><div style={{ fontSize: "10px", fontWeight: 600, color: C.textMuted, textTransform: "uppercase", letterSpacing: "0.08em", marginBottom: "4px" }}>Date</div><div style={{ fontSize: "14px" }}>{date}</div></div>
              <div><div style={{ fontSize: "10px", fontWeight: 600, color: C.textMuted, textTransform: "uppercase", letterSpacing: "0.08em", marginBottom: "4px" }}>Payment</div><div style={{ fontSize: "14px" }}>{paymentLabel}</div></div>
            </div>

            <div style={{ height: "1px", background: C.border, margin: "0 0 16px" }} />

            <div style={{ display: "flex", justifyContent: "space-between", marginBottom: "10px", fontSize: "14px" }}>
              <span style={{ color: C.textSec }}>Example Product</span><span>$149.00</span>
            </div>
            <div style={{ display: "flex", justifyContent: "space-between", marginBottom: "10px", fontSize: "14px" }}>
              <span style={{ color: C.textSec }}>Tax (25%)</span><span>$37.25</span>
            </div>
            <div style={{ height: "1px", background: C.border, margin: "6px 0 12px" }} />
            <div style={{ display: "flex", justifyContent: "space-between", fontSize: "18px", fontWeight: 700 }}>
              <span>Total</span><span>$186.25</span>
            </div>
          </div>

          {/* Download invoice button */}
          <button onClick={downloadInvoice} style={{ width: "100%", background: C.accent, color: "#fff", border: "none", borderRadius: "10px", padding: "14px", fontSize: "15px", fontWeight: 600, cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center", gap: "8px", marginBottom: "12px", fontFamily: "inherit", letterSpacing: "-0.01em" }}>
            <svg width="16" height="16" viewBox="0 0 16 16" fill="none"><path d="M8 2v8m0 0l-3-3m3 3l3-3M2 12v1a1 1 0 001 1h10a1 1 0 001-1v-1" stroke="#fff" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/></svg>
            Download Invoice
          </button>

          <a href="/" style={{ display: "block", background: C.surface, color: C.text, border: `1px solid ${C.borderStrong}`, borderRadius: "10px", padding: "14px", fontSize: "15px", fontWeight: 600, textDecoration: "none", textAlign: "center", letterSpacing: "-0.01em" }}>
            Back to start
          </a>
        </div>
      </main>

      <a href="https://sloth-studio.pages.dev" target="_blank" rel="noopener noreferrer" style={{ position: "fixed", bottom: "24px", right: "24px", background: C.surface2, border: `1px solid ${C.borderStrong}`, borderRadius: "100px", padding: "8px 16px", fontSize: "12px", color: C.textSec, textDecoration: "none", backdropFilter: "blur(8px)", boxShadow: "0 4px 16px rgba(0,0,0,0.4)", zIndex: 100 }}>Built by Sloth Studio</a>
      <style>{`@keyframes popIn { from { transform: scale(0); opacity: 0; } to { transform: scale(1); opacity: 1; } }`}</style>
    </div>
  );
}

export default function SuccessPage() {
  return (
    <Suspense fallback={<div style={{ minHeight: "100vh", background: "#09090B" }} />}>
      <SuccessContent />
    </Suspense>
  );
}
